name: allow_http
description: Use this package to allow HTTP network traffic.
version: 1.0.0
homepage: https://untillnesss.github.io
repository: https://github.com/untillnesss/allow-http.git

environment:
  sdk: ">=2.15.1 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
